name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang
homepage: https://github.com/pulyaevskiy/dart-kafka

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  quiver: ^3.0.1+1
  logging: ^1.0.2

dev_dependencies:
  test: ^1.21.0
  mockito: ^5.1.0
